import { motion } from "framer-motion";
import { ArrowUpRight } from "lucide-react";
import { itServices } from "../../data/informationTechnology";

export function ITServices() {
  return (
    <section id="services" className="bg-white py-20 md:py-28"><div className="mx-auto max-w-[1400px] px-6 xl:px-10"><div className="flex flex-col justify-between gap-5 border-b border-gray-200 pb-7 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.25em] text-[#A57C35]">What we do</p><h2 className="mt-4 text-[clamp(32px,4vw,52px)] font-semibold tracking-[-0.04em] text-[#222]">Technology Services</h2></div><p className="max-w-[320px] text-sm leading-6 text-[#777]">Practical technology services that keep our organisation moving.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{itServices.map((service, index) => { const Icon = service.icon; return <motion.article key={service.title} initial={{ opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.5, delay: index * 0.07 }} whileHover={{ y: -6 }} className="group border border-gray-200 bg-[#F8F7F4] p-7 transition-all duration-300 hover:border-[#C79A43] hover:bg-white hover:shadow-[0_18px_35px_rgba(12,36,68,0.08)]"><div className="flex items-start justify-between"><div className="flex h-11 w-11 items-center justify-center border border-[#C79A43]/45 text-[#A57C35] transition-colors group-hover:bg-[#C79A43] group-hover:text-white"><Icon size={21} strokeWidth={1.7} /></div><span className="text-xs text-gray-400">0{index + 1}</span></div><h3 className="mt-9 text-[19px] font-semibold text-[#222] transition-colors group-hover:text-[#A57C35]">{service.title}</h3><p className="mt-3 text-sm leading-7 text-[#777]">{service.description}</p><ArrowUpRight size={18} className="mt-7 text-[#C79A43] transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" /></motion.article>; })}</div></div></section>
  );
}
